# Generated by Django 2.1.15 on 2020-08-07 09:03

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('mobile', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.EmailField(default=None, max_length=20, null=True)),
                ('address', models.CharField(default=None, max_length=20, null=True)),
                ('postal_code', models.IntegerField(default=None, null=True)),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('customer_stars', models.IntegerField(default=0, null=True)),
                ('customer_points', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('unitPrice', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('paymentMethod', models.CharField(choices=[('Cash', 'Cash'), ('By Card', 'By Card')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Progress', 'Progress'), ('Ready', 'Ready'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('type', models.CharField(choices=[('Direct', 'Direct'), ('By Phone', 'By Phone'), ('By Online', 'By Online')], default='Direct', max_length=20)),
                ('deliveryType', models.CharField(choices=[('Take Away', 'Take Away'), ('Eat here', 'Eat here'), ('Home Delivery', 'Home Delivery')], default='Take Away', max_length=30)),
                ('total_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_no_of_items', models.PositiveIntegerField(default=1)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None, null=True)),
                ('customer_nick_name', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(default=1)),
                ('no_of_items', models.PositiveIntegerField(default=1)),
                ('unitPrice', models.FloatField(default=None)),
                ('extraPrice', models.FloatField(default=None)),
                ('user_input', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('total_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(default=1)),
                ('extras', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='extras', to='app.Extras')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.OrderItem')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('unitPrice', models.FloatField(default=None)),
                ('discountPercentage', models.FloatField(blank=True, default=None, null=True)),
                ('productType', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('image_path', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['seq_no'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='app.Product'),
        ),
    ]
