# Generated by Django 2.1.15 on 2020-08-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['seqNo']},
        ),
        migrations.RenameField(
            model_name='extras',
            old_name='create_date',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='extras',
            old_name='seq_no',
            new_name='seqNo',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='create_date',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_no_of_items',
            new_name='total_noOfItems',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='extraPrice',
            new_name='extrasPrice',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='no_of_items',
            new_name='noOfItems',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='seq_no',
            new_name='seqNo',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='user_input',
            new_name='userInput',
        ),
        migrations.RenameField(
            model_name='orderitemextras',
            old_name='seq_no',
            new_name='seqNo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_date',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_path',
            new_name='imagePath',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seq_no',
            new_name='seqNo',
        ),
    ]
