# Generated by Django 2.1.15 on 2020-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200807_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='unitPrice',
            field=models.FloatField(default=1.0),
        ),
    ]
